{"name": "test_get_created_user", "status": "failed", "statusDetails": {"message": "AssertionError: assert (404 == 200)\n +  where 404 = <Response [404]>.status_code", "trace": "self = <test_users.TestUsers object at 0x0000028804B66AD0>, url_reqres_in = 'https://reqres.in/api'\nfaker = <faker.generator.Generator object at 0x0000028804C3B890>\n\n    @pytest.mark.usefixtures(\"created_users\")\n    def test_get_created_user(self, url_reqres_in: str, faker: ModuleType):\n    \n        # Given\n        self.test_create_new_user(url_reqres_in, faker)\n    \n        print(url_reqres_in)\n        url = url_reqres_in + f'/users/{self.created_user_id}'\n        self.logger.info(\n            f'Get created user of id: {self.created_user_id} by get on: {url}')\n        # When\n        response = requests.get(url, headers=self.headers)\n    \n        response_dic = response.json()\n        # Then\n>       assert response.status_code == 200\\\n            and hasattr(response_dic, 'id')\nE       assert (404 == 200)\nE        +  where 404 = <Response [404]>.status_code\n\ntests\\test_users.py:113: AssertionError"}, "attachments": [{"name": "log", "source": "3c108e37-cf7e-4e83-ba65-ba1d7dbadf74-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "ef048fa6-b2e5-4c7b-8c2f-07db2efb6478-attachment.txt", "type": "text/plain"}], "start": 1678215467171, "stop": 1678215467585, "uuid": "615a68c2-9fa5-4688-aa7f-e345af421f8c", "historyId": "da0357306ea9568fba78ea9ca2ef9f2a", "testCaseId": "e297dc9d0bd9db3f485a67a39659e19b", "fullName": "tests.test_users.TestUsers#test_get_created_user", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('created_users')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_users"}, {"name": "subSuite", "value": "TestUsers"}, {"name": "host", "value": "LAPTOP-DKHHR5FU"}, {"name": "thread", "value": "25692-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_users"}]}